
function FileExists(const FileName: string;  FollowLink: Boolean = True ):Boolean;
function ChangeFileExt( const FileName: string; const Extension: string):string;
function IncludeTrailingPathDelimiter( const Path: string):string;
function ExtractFileName( const FileName: string):string;
function ExtractFilePath( const FileName: string):string;

function UpperCase( const s: string):string;
function AnsiUpperCase( const s: string ):string;



